### ISSUE TITLE
新建项目插入数据报错 top.tangyh.basic.utils.SpringUtils.parentApplicationContext" is null

### ISSUE THREAD

**Issue by 274574162** [zuihou/zuihou-admin-cloud#364]
# 前提
分支17/5.x
原项目启动成功，
新创建的项目，执行插入时，id自动注入
![image](https://github.com/user-attachments/assets/4e14af08-3d25-4f43-9907-70dd5a718f07)
![image](https://github.com/user-attachments/assets/daff0719-3d05-4fd4-852d-35a6dfc9f752)
添加了扫描包依然不行
@ComponentScan({
        UTIL_PACKAGE, BUSINESS_PACKAGE, "com.baidu.fsg"
})

错误日志

Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.NullPointerException: Cannot invoke "org.springframework.context.ApplicationContext.getBean(java.lang.Class)" because "top.tangyh.basic.utils.SpringUtils.parentApplicationContext" is null
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184) ~[mybatis-3.5.16.jar:3.5.16]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:569) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:333) ~[mybatis-spring-3.0.4.jar:3.0.4]
	... 120 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "org.springframework.context.ApplicationContext.getBean(java.lang.Class)" because "top.tangyh.basic.utils.SpringUtils.parentApplicationContext" is null
	at top.tangyh.basic.utils.SpringUtils.getBean(SpringUtils.java:64) ~[classes/:na]
	at top.tangyh.basic.database.config.LampMetaObjectHandler.fillId(LampMetaObjectHandler.java:72) ~[classes/:na]
	at top.tangyh.basic.database.config.LampMetaObjectHandler.insertFill(LampMetaObjectHandler.java:66) ~[classes/:na]

**Comment by 274574162** [comment]
![image](https://github.com/user-attachments/assets/0f13832a-7759-4f30-ac05-aab8808199e2)

**Comment by zuihou** [comment]
<img width="1295" alt="image" src="https://github.com/user-attachments/assets/ae0fc857-8030-4965-b926-9cdcec418c3d">

新建服务需要有一个配置类继承ta
