### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: com/alibaba/nacos/api/exception/NacosException

### ISSUE THREAD

**Issue by yangdecai** [zuihou/zuihou-admin-cloud#366]
# 前提

**️ 提问之前，请检查以下列表，如果忽略此问题模板，您的问题将直接关闭！**

- [x] 确保已经将文档clone到本地，并使用Markdown工具阅读了全文 [在线文档](https://tangyh.top/opendoc/%E7%AE%80%E4%BB%8B.html)
- [x] 确保你的代码是最新版本 或 下载最新版本代码能复现
- [x] 确保已经在 [issues](https://github.com/zuihou/lamp-cloud/issues)、 [discussions](https://github.com/zuihou/lamp-cloud/discussions) 、[google](https://google.com) 查找了相关问题

# 版本信息：

- JDK 版本(包括小版本号)(必填) :
  - [x] 17.x
- 项目模式(必填)：
  - [x]lamp-datasource-max

- 源码版本(必填)：
  - [x] 5.0.3

- MySQL(必填)：
  - [x] mysql 8.x.x

- Nacos(必填)： 2.4.3
- seata(必填)： 2.2.0

# 问题描述：
lamp-boot-server开启分布式事务isSeata: true
启动报错Caused by: java.lang.NoClassDefFoundError: com/alibaba/nacos/api/exception/NacosException
Caused by: java.lang.ClassNotFoundException: com.alibaba.nacos.api.exception.NacosException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 37 common frames omitted
然后我在lamp-boot-server的pom文件中添加了依赖，并在dev的mysql.yml文件中添加了相关配置
```
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    <exclusions>
        <exclusion>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-loadbalancer</artifactId>
</dependency>

<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
    <exclusions>
        <exclusion>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>com.alibaba.nacos</groupId>
    <artifactId>nacos-client</artifactId>
</dependency>
```
```
  nacos:
    ip: ${NACOS_IP:@nacos.ip@}
    port: ${NACOS_PORT:@nacos.port@}
    namespace: ${NACOS_NAMESPACE:@nacos.namespace@}
    username: ${NACOS_USERNAME:@nacos.username@}
    password: ${NACOS_PASSWORD:@nacos.password@}
  seata:
    ip: ${SEATA_IP:@seata.ip@}
    port: ${SEATA_PORT:@seata.port@}
    namespace: ${SEATA_NAMESPACE:@seata.namespace@}
  sentinel:
    dashboard: ${SENTINEL_DASHBOARD:@sentinel.dashboard@}
```
启动后提示http error, code=403,msg=user not found!,dataId=lamp-boot-server-datasource,group=DEFAULT_GROUP,tenant=

# 报错日志
```
[lamp-boot-server-datasource:18760::] 2024-12-26 15:51:34.424:[ERROR] [19148] [] [main:8169] [c.a.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData:111] get data from Nacos error,dataId:lamp-boot-server-datasource 

com.alibaba.nacos.api.exception.NacosException: http error, code=403,msg=user not found!,dataId=lamp-boot-server-datasource,group=DEFAULT_GROUP,tenant=
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfigInner(ClientWorker.java:1198) ~[nacos-client-2.4.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:1157) ~[nacos-client-2.4.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:476) ~[nacos-client-2.4.3.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:188) ~[nacos-client-2.4.3.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:99) ~[nacos-client-2.4.3.jar:na]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:89) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:74) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosPropertySource(NacosPropertySourceLocator.java:199) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:186) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadApplicationConfiguration(NacosPropertySourceLocator.java:141) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:103) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:50) ~[spring-cloud-context-4.1.5.jar:4.1.5]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:46) ~[spring-cloud-context-4.1.5.jar:4.1.5]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.doInitialize(PropertySourceBootstrapConfiguration.java:121) ~[spring-cloud-context-4.1.5.jar:4.1.5]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:111) ~[spring-cloud-context-4.1.5.jar:4.1.5]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:627) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:401) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.6.jar:3.3.6]
	at top.tangyh.lamp.common.ServerApplication.start(ServerApplication.java:20) ~[classes/:na]
	at top.tangyh.lamp.BootServerApplication.main(BootServerApplication.java:38) ~[classes/:na]

[lamp-boot-server-datasource:18760::] 2024-12-26 15:51:34.444:[ERROR] [19148] [] [main:8189] [c.a.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData:111] get data from Nacos error,dataId:lamp-boot-server-datasource.properties 

com.alibaba.nacos.api.exception.NacosException: http error, code=403,msg=user not found!,dataId=lamp-boot-server-datasource.properties,group=DEFAULT_GROUP,tenant=
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfigInner(ClientWorker.java:1198) ~[nacos-client-2.4.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:1157) ~[nacos-client-2.4.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:476) ~[nacos-client-2.4.3.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:188) ~[nacos-client-2.4.3.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:99) ~[nacos-client-2.4.3.jar:na]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:89) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:74) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosPropertySource(NacosPropertySourceLocator.java:199) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:186) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadApplicationConfiguration(NacosPropertySourceLocator.java:144) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:103) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:50) ~[spring-cloud-context-4.1.5.jar:4.1.5]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:46) ~[spring-cloud-context-4.1.5.jar:4.1.5]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.doInitialize(PropertySourceBootstrapConfiguration.java:121) ~[spring-cloud-context-4.1.5.jar:4.1.5]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:111) ~[spring-cloud-context-4.1.5.jar:4.1.5]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:627) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:401) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.6.jar:3.3.6]
	at top.tangyh.lamp.common.ServerApplication.start(ServerApplication.java:20) ~[classes/:na]
	at top.tangyh.lamp.BootServerApplication.main(BootServerApplication.java:38) ~[classes/:na]

[lamp-boot-server-datasource:18760::] 2024-12-26 15:51:34.450:[ERROR] [19148] [] [main:8195] [c.a.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData:111] get data from Nacos error,dataId:lamp-boot-server-datasource-dev.properties 

com.alibaba.nacos.api.exception.NacosException: http error, code=403,msg=user not found!,dataId=lamp-boot-server-datasource-dev.properties,group=DEFAULT_GROUP,tenant=
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfigInner(ClientWorker.java:1198) ~[nacos-client-2.4.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:1157) ~[nacos-client-2.4.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:476) ~[nacos-client-2.4.3.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:188) ~[nacos-client-2.4.3.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:99) ~[nacos-client-2.4.3.jar:na]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:89) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:74) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosPropertySource(NacosPropertySourceLocator.java:199) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:186) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadApplicationConfiguration(NacosPropertySourceLocator.java:149) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:103) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.2.jar:2023.0.1.2]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:50) ~[spring-cloud-context-4.1.5.jar:4.1.5]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:46) ~[spring-cloud-context-4.1.5.jar:4.1.5]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.doInitialize(PropertySourceBootstrapConfiguration.java:121) ~[spring-cloud-context-4.1.5.jar:4.1.5]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:111) ~[spring-cloud-context-4.1.5.jar:4.1.5]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:627) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:401) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.6.jar:3.3.6]
	at top.tangyh.lamp.common.ServerApplication.start(ServerApplication.java:20) ~[classes/:na]
	at top.tangyh.lamp.BootServerApplication.main(BootServerApplication.java:38) ~[classes/:na]
```
```
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
[lamp-boot-server-datasource:18760::] 2024-12-26 15:51:43.473:[ERROR] [19148] [] [main:17218] [org.springframework.boot.SpringApplication.reportFailure:859] Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'globalTransactionScanner' defined in class path resource [org/apache/seata/spring/boot/autoconfigure/SeataAutoConfiguration.class]: no available service found in cluster.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1806) ~[spring-beans-6.1.15.jar:6.1.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.15.jar:6.1.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.15.jar:6.1.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.15.jar:6.1.15]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.15.jar:6.1.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.15.jar:6.1.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205) ~[spring-beans-6.1.15.jar:6.1.15]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:265) ~[spring-context-6.1.15.jar:6.1.15]
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:806) ~[spring-context-6.1.15.jar:6.1.15]
	at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:609) ~[spring-context-6.1.15.jar:6.1.15]
	at org.springframework.context.support.AbstractApplicationContext.jrLockAndRefresh(AbstractApplicationContext.java:41002) ~[spring-context-6.1.15.jar:6.1.15]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:42008) ~[spring-context-6.1.15.jar:6.1.15]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.6.jar:3.3.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.6.jar:3.3.6]
	at top.tangyh.lamp.common.ServerApplication.start(ServerApplication.java:20) ~[classes/:na]
	at top.tangyh.lamp.BootServerApplication.main(BootServerApplication.java:38) ~[classes/:na]
Caused by: org.apache.seata.common.exception.FrameworkException: no available service found in cluster.
	at org.apache.seata.core.rpc.netty.NettyClientChannelManager.throwFailFastException(NettyClientChannelManager.java:336) ~[seata-all-2.2.0.jar:2.2.0]
	at org.apache.seata.core.rpc.netty.NettyClientChannelManager.doReconnect(NettyClientChannelManager.java:208) ~[seata-all-2.2.0.jar:2.2.0]
	at org.apache.seata.core.rpc.netty.NettyClientChannelManager.initReconnect(NettyClientChannelManager.java:176) ~[seata-all-2.2.0.jar:2.2.0]
	at org.apache.seata.core.rpc.netty.TmNettyRemotingClient.initConnection(TmNettyRemotingClient.java:291) ~[seata-all-2.2.0.jar:2.2.0]
	at org.apache.seata.core.rpc.netty.TmNettyRemotingClient.init(TmNettyRemotingClient.java:191) ~[seata-all-2.2.0.jar:2.2.0]
	at org.apache.seata.tm.TMClient.init(TMClient.java:47) ~[seata-all-2.2.0.jar:2.2.0]
	at org.apache.seata.spring.annotation.GlobalTransactionScanner.initClient(GlobalTransactionScanner.java:247) ~[seata-all-2.2.0.jar:2.2.0]
	at org.apache.seata.spring.annotation.GlobalTransactionScanner.afterPropertiesSet(GlobalTransactionScanner.java:495) ~[seata-all-2.2.0.jar:2.2.0]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853) ~[spring-beans-6.1.15.jar:6.1.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1802) ~[spring-beans-6.1.15.jar:6.1.15]
	... 19 common frames omitted
```
# 报错截图
<img width="1619" alt="微信图片_20241226155729" src="https://github.com/user-attachments/assets/cc1f0eb4-2d19-4ae0-90ff-1fcb35c0e5a1" />

<img width="1426" alt="微信图片_20241226155729" src="https://github.com/user-attachments/assets/ebac709a-b145-4a2b-ae1c-9ebc02a613c5" />

# 重现步骤
config-dev.properties配置信息，这个配置信息在微服务模式下已经正常启动项目
```
## 仅微服务版会使用的参数
nacos.ip=127.0.0.1
nacos.port=8848
# 独立命名空间避免跟别的项目冲突
nacos.namespace=2d09714b-5693-46bc-83ab-8c8d0e192f76
nacos.username=nacos
nacos.password=nacos

# seata 客户端从 nacos 拉取配置和注册的命名空间 跟 nacos.namespace 区分出来，原因是 seata
seata.namespace=5b51e46a-4aeb-4d40-8398-8a9d33e2f0ad
# seata 的 grouplist ip
seata.ip=127.0.0.1
# seata 的 grouplist 端口
seata.port=8091

# sentinel 控制台
sentinel.dashboard=127.0.0.1:8088

# mysql.yml  oracle.yml sqlserver.yml
database.type=mysql.yml

## 单体版和微服务版都会使用的参数
# 日志存储路径
logging.file.path=./logs
```
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
已修复，同时阅读一下新写的文档： https://tangyh.top/doc/start/boot/Nacos%E5%92%8CSeata%E5%90%AF%E5%8A%A8.html

**Comment by zuihou** [comment]
更新代码后，无需修改pom文件中的依赖
