### ISSUE TITLE
启动 gateway报错，引包

### ISSUE THREAD

**Issue by huangzhanqiao** [zuihou/zuihou-admin-cloud#6]
Caused by: java.lang.NoClassDefFoundError: org/springframework/cloud/client/loadbalancer/LoadBalancedRetryFactory

java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.openfeign.ribbon.FeignRibbonClientAutoConfiguration] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:656)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:553)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:538)
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:596)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:727)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:669)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:637)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1494)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:414)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:384)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:504)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:497)
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1183)
	at org.springframework.boot.SpringApplication.getExitCodeFromMappedException(SpringApplication.java:879)
	at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:865)
	at org.springframework.boot.SpringApplication.handleExitCode(SpringApplication.java:851)
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:802)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1245)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1233)

**Comment by bing086** [comment]
也碰到同样问题，解决了吗

**Comment by huangzhanqiao** [comment]
没有。。。等版主消息呢

在 2018-06-08 13:31:50，"bing086" <notifications@github.com> 写道：


也碰到同样问题，解决了吗

**Comment by lehui20082008** [comment]
怎么解决的？
